import type { GetServerSideProps, NextPage } from 'next'
import { Fragment, createElement } from "react";
import Head from 'next/head'
import Image from 'next/image'
import { getList } from '../lib/microcms'
import styles from '../styles/Home.module.css'

import { unified } from "unified";
import parse from "rehype-parse";
import rehypeReact from "rehype-react";
import { CustomParagraph } from '../components/CustomPragraph';

const parseHtml = (content: string) => {
  const htmlAst = unified()
    .use(parse, { fragment: true })
    .use(rehypeReact, {
      createElement,
      Fragment,
      components: {
        p: (props) => <CustomParagraph {...props} />,
        // a: (props) => <CustomLink {...props} />,
      },
    })
    .processSync(content).result;
  return htmlAst;
};

const Home: NextPage = ({ data }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>タイトル</h1>
        <section style={{ border: "solid blue 5px", padding: "0 20px" }}>
          <h2>ヘッダーバナーフィールド</h2>
          <h2>{data.carInsurance.title}</h2>
          <Image src={data.carInsurance.bgImage.url} height={data.carInsurance.bgImage.height} width={data.carInsurance.bgImage.width} />
          <p>{data.carInsurance.bodyText}</p>
        </section>
        <section style={{ border: "solid green 5px", padding: "0 20px", margin: "30px 0" }}>
          <h2>目次のフィールド</h2>
          {parseHtml(data.contentIndex.textList)}
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {
  const data = await getList();
  return { props: { data: data } };
}
