name: Deploy
on:
  repository_dispatch:
    types: [update_post]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: yarn
    # - env: 
    #     NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN: ${{ env.NEXT_PUBLIC_MICROCMS_SERVICE_DOMAIN }}
    #     NEXT_PUBLIC_MICROCMS_API_KEY: ${{ env.NEXT_PUBLIC_MICROCMS_API_KEY }}
    - run: yarn build
    - run: yarn deploy
